---
  # This playbook sucks 
- name: Installation du serveur
  hosts: web
  remote_user: arnaud
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: installation de 
      apt: name={{PACKAGE}}
      #apt: name=icinga2
    # Add specified repository into sources list.
    
    


